# Generated by Django 5.1.5 on 2025-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('create_date', models.DateField(auto_now=True)),
                ('create_by', models.CharField(max_length=100)),
            ],
        ),
    ]
